# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TxgBlog', '0002_auto_20180322_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='article',
        ),
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.CharField(default='2411771853@qq.com', max_length=50, verbose_name='\u90ae\u7bb1'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default='\u6765\u5440\uff0c\u7559\u8a00\u5440\uff01', verbose_name='\u8bc4\u8bba\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.CharField(default='vision', max_length=50, verbose_name='\u7528\u6237'),
        ),
    ]
