# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TxgBlog', '0003_auto_20180322_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(max_length=300, verbose_name='\u6587\u7ae0\u63cf\u8ff0'),
        ),
    ]
